[versions]

boot2 = "2.7.12"
dsproxy = "1.9"
findbugs = "3.0.2"
jackson = "2.13.5"
jsonpath = "2.7.0"
junit = "5.8.2"
mapstruct = "1.5.5.Final"
orgjson = "20230227"
sleuth = "3.1.8"
slf4j = "1.7.36"
spring = "5.3.27"
testcontainers = "1.18.0"
truth = "1.1.3"
