[versions]

boot2 = "2.7.12"
dsproxy = "1.9"
errorprone = "2.19.1"
findbugs = "3.0.2"
junit-pioneer = "2.0.1"
mapstruct = "1.5.5.Final"
nullaway = "0.10.10"
orgjson = "20230227"
sleuth = "3.1.8"
testcontainers = "1.18.3"
truth = "1.1.4"
