[versions]
boot2 = "2.7.18"
boot3 = "3.0.13"
boot31 = "3.1.12"
boot32 = "3.2.12"
boot33 = "3.3.9"
boot34 = "3.4.3"

archunit = "1.4.0"
dsproxy = "1.9"
errorprone = "2.36.0"
immutables = "2.10.1"
jdbi = "3.48.0"
jspecify = "1.0.0"
junit-bom = "5.12.0"
junit-pioneer = "2.3.0"
logcaptor = "2.10.1"
mapstruct = "1.6.3"
nullaway = "0.12.4"
orgjson = "20250107"
picnic-errorprone = "0.20.0"
sleuth = "3.1.11"
streamex = "0.8.3"
testcontainers = "1.20.5"
truth = "1.4.4"
