[versions]
boot2 = "2.7.18"
boot3 = "3.0.13"
boot31 = "3.1.12"
boot32 = "3.2.7"
boot33 = "3.3.1"

archunit = "1.3.0"
dsproxy = "1.9"
errorprone = "2.28.0"
findbugs = "3.0.2"
jbannotations = "24.1.0"
jdbi = "3.45.2"
junit-bom = "5.10.3"
junit-pioneer = "2.2.0"
mapstruct = "1.5.5.Final"
nullaway = "0.11.0"
orgjson = "20240303"
sleuth = "3.1.11"
testcontainers = "1.19.8"
truth = "1.4.4"
