[versions]

boot2 = "2.7.12"
boot3 = "3.0.7"
boot31 = "3.1.0"
dsproxy = "1.9"
errorprone = "2.20.0"
findbugs = "3.0.2"
jbannotations = "24.0.1"
junit-pioneer = "2.0.1"
mapstruct = "1.5.5.Final"
nullaway = "0.10.10"
orgjson = "20230227"
sleuth = "3.1.8"
testcontainers = "1.18.3"
truth = "1.1.4"
