[versions]
boot2 = "2.7.18"
boot3 = "3.0.13"
boot31 = "3.1.7"

archunit = "1.2.1"
dsproxy = "1.9"
errorprone = "2.24.1"
findbugs = "3.0.2"
jbannotations = "24.0.1"
jdbi = "3.43.0"
junit-bom = "5.10.0"
junit-pioneer = "2.0.1"
mapstruct = "1.5.5.Final"
nullaway = "0.10.21"
orgjson = "20230618"
sleuth = "3.1.9"
testcontainers = "1.19.3"
truth = "1.1.5"
