---
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_REUSE_ENABLE: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Pull containers images
        run: docker compose pull

      - name: Build and test for Spring Boot 2
        uses: burrunan/gradle-cache-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          job-id: sb2
          arguments: --scan build sonar
          properties: |
            testBootVariant=2

      - name: Test for Spring Boot 3.0
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: sb3.0
          arguments: test
          properties: |
            testBootVariant=3.0

      - name: Test for Spring Boot 3.1
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: sb3.1
          arguments: test
          properties: |
            testBootVariant=3.1

      - name: Test for Spring Boot 3.2
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: sb3.2
          arguments: test
          properties: |
            testBootVariant=3.2

      - name: Test for Spring Boot 3.3
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: sb3.3
          arguments: test
          properties: |
            testBootVariant=3.3

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: test-results
          path: '**/build/reports/**'
...
