---
name: Build

on:
  workflow_dispatch:
  push:

jobs:
  ci-build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_REUSE_ENABLE: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Build and test for Spring Boot 2
        run: ./gradlew --stacktrace -PtestBootVariant=2 clean build

      - name: Coveralls
        run: ./gradlew --stacktrace coverallsJacoco
        if: env.COVERALLS_REPO_TOKEN != null
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Migrate Test Application to Spring Boot 3
        run: ./gradlew --quiet --stacktrace rewriteRun

      - name: Test for Spring Boot 3.0
        run: ./gradlew --stacktrace -PtestBootVariant=30 test

      - name: Test for Spring Boot 3.1
        run: ./gradlew --stacktrace -PtestBootVariant=31 test

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: test-results
          path: '**/build/reports/**'
...
