---
name: Build

on:
  workflow_dispatch:
  push:

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Build and test for Spring Boot 2
        run: ./gradlew --no-daemon --stacktrace -PtestBootVariant=2 clean build

      - name: Migrate Test Application to Spring Boot 3
        run: ./gradlew --no-daemon --stacktrace rewriteRun

      - name: Test for Spring Boot 3.0
        run: ./gradlew --no-daemon --stacktrace -PtestBootVariant=30 test

      - name: Test for Spring Boot 3.1
        run: ./gradlew --no-daemon --stacktrace -PtestBootVariant=31 test
...
